### ISSUE TITLE
Is this extension compatible with PHP7?

### ISSUE THREAD

**Issue by julianmurillo** [ikonoshirt/pbkdf2#30]
Thanks for the attention.

**Comment by Schrank** [comment]
@julianmurillo that is a good questions 🤔 did you try it? I would assume yes. Sorry for the really late answer - I once unsubscribed ALL my repos - fixed that for this now

**Comment by tobihille** [comment]
We have it running on php 7.3, it's working fine.

**Comment by julianmurillo** [comment]
Thank you so much
