### ISSUE TITLE
Magento 2 Support

### ISSUE THREAD

**Issue by bk-one** [ikonoshirt/pbkdf2#33]
Are there any plans for Magento 2 support? I have a magento 1 installation that I want to upgrade and it's not working out of the box.

**Comment by Schrank** [comment]
Hi Ben,

sorry to tell you but no. I don't know how Magento 2 is doing password validation, so maybe one can implement the check on login (as this extension) and then tell M2, that the hashing algorithm is legacy and M2 rehashes the password.

But I don't plan to release an M2 version of this module.

Best
Fabian
